apiVersion: v2
name: theia-shared-cache
description: A Gradle Build Cache server with Redis backend for Theia IDE deployments in Kubernetes

type: application

# Chart version - bump for breaking changes
version: 0.3.0

# Application version - matches the cache server version
appVersion: "0.1.0"

dependencies:
  - name: reposilite
    version: "1.3.25"
    repository: "https://helm.reposilite.com/"
    condition: reposilite.enabled
