{{- if .Values.ui.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: theia-shared-cache-ui
  labels:
    app.kubernetes.io/name: theia-shared-cache
    app.kubernetes.io/instance: theia-shared-cache
    app.kubernetes.io/component: ui
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.hosts.configuration.cache }}.{{ .Values.hosts.configuration.baseHost }}
      secretName: cache-cert-secret  # References the cert created by theia-certificates
  rules:
    - host: {{ .Values.hosts.configuration.cache }}.{{ .Values.hosts.configuration.baseHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: theia-shared-cache
                port:
                  number: 5071
{{- end }}
