apiVersion: v1
kind: Service
metadata:
  name: theia-shared-cache
  labels:
    app.kubernetes.io/name: theia-shared-cache
    app.kubernetes.io/instance: theia-shared-cache
spec:
  selector:
    app.kubernetes.io/name: theia-shared-cache
    app.kubernetes.io/instance: theia-shared-cache
  ports:
    - name: http
      port: 5071
      targetPort: 5071
    - name: grpc-bazel
      port: 6011
      targetPort: 6011
