global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "gradle-cache"
    static_configs:
      - targets: ["cache-server:8080"]
    metrics_path: /metrics
  - job_name: "redis"
    static_configs:
      - targets: ["redis-exporter:9121"]
  - job_name: "reposilite"
    static_configs:
      - targets: ["reposilite:8081"]
    metrics_path: /api/prometheus
