{{- if and .Values.cacheServer.tls.enabled .Values.cacheServer.tls.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-tls
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: cache-server
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  secretName: {{ .Values.cacheServer.tls.secretName }}
  issuerRef:
    name: {{ .Values.cacheServer.tls.certManager.issuerName }}
    kind: {{ .Values.cacheServer.tls.certManager.issuerKind }}
  dnsNames:
    - {{ .Release.Name }}-cache-server
    - {{ .Release.Name }}-cache-server.{{ .Release.Namespace }}
    - {{ .Release.Name }}-cache-server.{{ .Release.Namespace }}.svc
    - {{ .Release.Name }}-cache-server.{{ .Release.Namespace }}.svc.cluster.local
{{- end }}
