apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-minio
  labels:
    app: {{ .Release.Name }}
    component: storage
spec:
  type: ClusterIP
  ports:
    - name: api
      port: 9000
      targetPort: api
      protocol: TCP
    - name: console
      port: 9001
      targetPort: console
      protocol: TCP
  selector:
    app: {{ .Release.Name }}
    component: storage
