{{- if .Values.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    app: {{ .Release.Name }}
type: Opaque
data:
  minio-access-key: {{ "minioadmin" | b64enc | quote }}
  minio-secret-key: {{ "minioadmin" | b64enc | quote }}
  {{- if .Values.auth.enabled }}
  cache-password: {{ .Values.auth.password | b64enc | quote }}
  {{- end }}
{{- end }}
