{{- if or .Values.cacheServer.enabled .Values.minio.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{- if .Values.minio.enabled }}
  minio-access-key: {{ .Values.minio.auth.accessKey | b64enc | quote }}
  minio-secret-key: {{ .Values.minio.auth.secretKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.cacheServer.enabled }}
  cache-password: {{ .Values.cacheServer.auth.password | b64enc | quote }}
  {{- end }}
{{- end }}
