{{- if .Values.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-redis-secret
  labels:
    {{- include "theia-shared-cache.labels" . | nindent 4 }}
    app.kubernetes.io/component: storage
type: Opaque
data:
  {{- $secretName := printf "%s-redis-secret" .Release.Name }}
  {{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName }}
  {{- if $existingSecret }}
  redis-password: {{ index $existingSecret.data "redis-password" }}
  {{- else }}
  redis-password: {{ randAlphaNum 32 | b64enc}}
  {{- end }}
  cache-password: {{ .Values.auth.password | b64enc | quote}}
{{- end }}
