{{- if .Values.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-redis-secret
  labels:
    app: {{ .Release.Name }}
type: Opaque
data:
  {{- $secretName := printf "%s-redis-secret" .Release.Name }}
  {{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName }}
  {{- if $existingSecret }}
  redis-password: {{ index $existingSecret.data "redis-password" }}
  {{- else }}
  redis-password: {{ randAlphaNum 32 | b64enc}}
  {{- end }}
{{- end }}
