# Minimal values for theia-shared-cache chart
replicaCount: 1

image:
  repository: gradle/build-cache-node
  tag: "21.2"
  pullPolicy: IfNotPresent

tls:
  enabled: false

# Persistence: used for StatefulSet volumeClaimTemplates
persistence:
  size: 10Gi
  storageClass: "standard"

# Resources applied to the container. Keep empty to use cluster defaults.
resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "10Gi"
    cpu: "1000m"

# UI Ingress Configuration
ui:
  enabled: false # Set to true to enable the web UI

hosts:
  configuration:
    baseHost: ""
    cache: ""
