apiVersion: v1
kind: Service
metadata:
  name: {{ include "theia-shared-cache.fullname" . }}-node
  labels:
    app.kubernetes.io/name: {{ include "theia-shared-cache.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "theia-shared-cache.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: 5071
      targetPort: 5071
    - name: grpc-bazel
      port: 6011
      targetPort: 6011
