apiVersion: v1
kind: Service
metadata:
  name: { { include "cache-node.fullname" . } }
  labels: { { - include "cache-node.labels" . | nindent 4 } }
spec:
  selector:
    app.kubernetes.io/part-of: gradle-enterprise
    app.kubernetes.io/component: build-cache-node
  ports:
    - name: http
      port: 5071
      targetPort: http
      protocol: TCP
    - name: grpc-bazel
      port: 6011
      targetPort: grpc-bazel
      protocol: TCP
