apiVersion: v1
kind: Service
metadata:
  name: build-cache-node
spec:
  selector:
    app.kubernetes.io/part-of: gradle-enterprise
    app.kubernetes.io/component: build-cache-node
  ports:
    - name: http
      port: 5071
    - name: grpc-bazel
      port: 6011
